#!/bin/bash -u
REGISTRATION_SCRIPT="/Users/mkuczyns/Projects/DYNACT2/dynact2/wbct_to_dynact_registration.py"
TRANSFORMATION_SCRIPT="/Users/mkuczyns/Projects/DYNACT2/dynact2/transform.py"

#--------------
# DYNACT2_200
#--------------
WBCT_MC1_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_200/DYNACT2_200_WBCT/DYNACT2_200_WBCT_RECON_MC1_REORIENT.nii"
WBCT_MC1_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_200/DYNACT2_200_WBCT/DYNACT2_200_WBCT_RECON_MC1_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_MC1="/Volumes/LaCie/DYNACT2/models/DYNACT2_200/DYNACT2_200_ABAD/RESAMPLED/DYNACT2_200_WBCT_TO_DYNACT_MC1_INIT.txt"

WBCT_TRP_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_200/DYNACT2_200_WBCT/DYNACT2_200_WBCT_RECON_TRP_REORIENT.nii"
WBCT_TRP_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_200/DYNACT2_200_WBCT/DYNACT2_200_WBCT_RECON_TRP_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_TRP="/Volumes/LaCie/DYNACT2/models/DYNACT2_200/DYNACT2_200_ABAD/RESAMPLED/DYNACT2_200_WBCT_TO_DYNACT_TRP_INIT.txt"

DYNACT_ABAD_VOL1="/Volumes/LaCie/DYNACT2/models/DYNACT2_200/DYNACT2_200_ABAD/RESAMPLED/VOLUME_1_RESAMPLED.nii"
OUTPUT_PATH="/Volumes/LaCie/DYNACT2/models/DYNACT2_200/DYNACT2_200_ABAD/RESAMPLED"

# Registration
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\" DYNACT2_200_MC1 \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\" DYNACT2_200_TRP \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd

# Transformation
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd

#--------------
# DYNACT2_201
#--------------
WBCT_MC1_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_201/DYNACT2_201_WBCT/DYNACT2_201_WBCT_RECON_MC1_REORIENT.nii"
WBCT_MC1_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_201/DYNACT2_201_WBCT/DYNACT2_201_WBCT_RECON_MC1_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_MC1="/Volumes/LaCie/DYNACT2/models/DYNACT2_201/DYNACT2_201_ABAD/RESAMPLED/DYNACT2_201_WBCT_TO_DYNACT_MC1_INIT.txt"

WBCT_TRP_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_201/DYNACT2_201_WBCT/DYNACT2_201_WBCT_RECON_TRP_REORIENT.nii"
WBCT_TRP_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_201/DYNACT2_201_WBCT/DYNACT2_201_WBCT_RECON_TRP_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_TRP="/Volumes/LaCie/DYNACT2/models/DYNACT2_201/DYNACT2_201_ABAD/RESAMPLED/DYNACT2_201_WBCT_TO_DYNACT_TRP_INIT.txt"

DYNACT_ABAD_VOL1="/Volumes/LaCie/DYNACT2/models/DYNACT2_201/DYNACT2_201_ABAD/RESAMPLED/VOLUME_1_RESAMPLED.nii"
OUTPUT_PATH="/Volumes/LaCie/DYNACT2/models/DYNACT2_201/DYNACT2_201_ABAD/RESAMPLED"

# Registration
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\" DYNACT2_201_MC1 \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\" DYNACT2_201_TRP \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd

# Transformation
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd

#--------------
# DYNACT2_202
#--------------
WBCT_MC1_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_202/DYNACT2_202_WBCT/DYNACT2_202_WBCT_RECON_MC1_REORIENT.nii"
WBCT_MC1_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_202/DYNACT2_202_WBCT/DYNACT2_202_WBCT_RECON_MC1_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_MC1="/Volumes/LaCie/DYNACT2/models/DYNACT2_202/DYNACT2_202_ABAD/RESAMPLED/DYNACT2_202_WBCT_TO_DYNACT_MC1_INIT.txt"

WBCT_TRP_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_202/DYNACT2_202_WBCT/DYNACT2_202_WBCT_RECON_TRP_REORIENT.nii"
WBCT_TRP_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_202/DYNACT2_202_WBCT/DYNACT2_202_WBCT_RECON_TRP_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_TRP="/Volumes/LaCie/DYNACT2/models/DYNACT2_202/DYNACT2_202_ABAD/RESAMPLED/DYNACT2_202_WBCT_TO_DYNACT_TRP_INIT.txt"

DYNACT_ABAD_VOL1="/Volumes/LaCie/DYNACT2/models/DYNACT2_202/DYNACT2_202_ABAD/RESAMPLED/VOLUME_1_RESAMPLED.nii"
OUTPUT_PATH="/Volumes/LaCie/DYNACT2/models/DYNACT2_202/DYNACT2_202_ABAD/RESAMPLED"

# Registration
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\" DYNACT2_202_MC1 \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\" DYNACT2_202_TRP \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd

# Transformation
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd

#--------------
# DYNACT2_203
#--------------
WBCT_MC1_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_203/DYNACT2_203_WBCT/DYNACT2_203_WBCT_RECON_MC1_REORIENT.nii"
WBCT_MC1_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_203/DYNACT2_203_WBCT/DYNACT2_203_WBCT_RECON_MC1_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_MC1="/Volumes/LaCie/DYNACT2/models/DYNACT2_203/DYNACT2_203_ABAD/RESAMPLED/DYNACT2_203_WBCT_TO_DYNACT_MC1_INIT.txt"

WBCT_TRP_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_203/DYNACT2_203_WBCT/DYNACT2_203_WBCT_RECON_TRP_REORIENT.nii"
WBCT_TRP_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_203/DYNACT2_203_WBCT/DYNACT2_203_WBCT_RECON_TRP_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_TRP="/Volumes/LaCie/DYNACT2/models/DYNACT2_203/DYNACT2_203_ABAD/RESAMPLED/DYNACT2_203_WBCT_TO_DYNACT_TRP_INIT.txt"

DYNACT_ABAD_VOL1="/Volumes/LaCie/DYNACT2/models/DYNACT2_203/DYNACT2_203_ABAD/RESAMPLED/VOLUME_1_RESAMPLED.nii"
OUTPUT_PATH="/Volumes/LaCie/DYNACT2/models/DYNACT2_203/DYNACT2_203_ABAD/RESAMPLED"

# Registration
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\" DYNACT2_203_MC1 \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\" DYNACT2_203_TRP \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd

# Transformation
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd

#--------------
# DYNACT2_204
#--------------
WBCT_MC1_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_204/DYNACT2_204_WBCT/DYNACT2_204_WBCT_RECON_MC1_REORIENT.nii"
WBCT_MC1_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_204/DYNACT2_204_WBCT/DYNACT2_204_WBCT_RECON_MC1_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_MC1="/Volumes/LaCie/DYNACT2/models/DYNACT2_204/DYNACT2_204_ABAD/RESAMPLED/DYNACT2_204_WBCT_TO_DYNACT_MC1_INIT.txt"

WBCT_TRP_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_204/DYNACT2_204_WBCT/DYNACT2_204_WBCT_RECON_TRP_REORIENT.nii"
WBCT_TRP_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_204/DYNACT2_204_WBCT/DYNACT2_204_WBCT_RECON_TRP_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_TRP="/Volumes/LaCie/DYNACT2/models/DYNACT2_204/DYNACT2_204_ABAD/RESAMPLED/DYNACT2_204_WBCT_TO_DYNACT_TRP_INIT.txt"

DYNACT_ABAD_VOL1="/Volumes/LaCie/DYNACT2/models/DYNACT2_204/DYNACT2_204_ABAD/RESAMPLED/VOLUME_1_RESAMPLED.nii"
OUTPUT_PATH="/Volumes/LaCie/DYNACT2/models/DYNACT2_204/DYNACT2_204_ABAD/RESAMPLED"

# Registration
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\" DYNACT2_204_MC1 \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\" DYNACT2_204_TRP \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd

# Transformation
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd

#--------------
# DYNACT2_205
#--------------
WBCT_MC1_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_205/DYNACT2_205_WBCT/DYNACT2_205_WBCT_RECON_MC1_REORIENT.nii"
WBCT_MC1_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_205/DYNACT2_205_WBCT/DYNACT2_205_WBCT_RECON_MC1_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_MC1="/Volumes/LaCie/DYNACT2/models/DYNACT2_205/DYNACT2_205_ABAD/RESAMPLED/DYNACT2_205_WBCT_TO_DYNACT_MC1_INIT.txt"

WBCT_TRP_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_205/DYNACT2_205_WBCT/DYNACT2_205_WBCT_RECON_TRP_REORIENT.nii"
WBCT_TRP_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_205/DYNACT2_205_WBCT/DYNACT2_205_WBCT_RECON_TRP_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_TRP="/Volumes/LaCie/DYNACT2/models/DYNACT2_205/DYNACT2_205_ABAD/RESAMPLED/DYNACT2_205_WBCT_TO_DYNACT_TRP_INIT.txt"

DYNACT_ABAD_VOL1="/Volumes/LaCie/DYNACT2/models/DYNACT2_205/DYNACT2_205_ABAD/RESAMPLED/VOLUME_1_RESAMPLED.nii"
OUTPUT_PATH="/Volumes/LaCie/DYNACT2/models/DYNACT2_205/DYNACT2_205_ABAD/RESAMPLED"

# Registration
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\" DYNACT2_205_MC1 \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\" DYNACT2_205_TRP \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd

# Transformation
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd

#--------------
# DYNACT2_207
#--------------
WBCT_MC1_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_207/DYNACT2_207_WBCT/DYNACT2_207_WBCT_RECON_MC1_REORIENT.nii"
WBCT_MC1_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_207/DYNACT2_207_WBCT/DYNACT2_207_WBCT_RECON_MC1_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_MC1="/Volumes/LaCie/DYNACT2/models/DYNACT2_207/DYNACT2_207_ABAD/RESAMPLED/DYNACT2_207_WBCT_TO_DYNACT_MC1_INIT.txt"

WBCT_TRP_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_207/DYNACT2_207_WBCT/DYNACT2_207_WBCT_RECON_TRP_REORIENT.nii"
WBCT_TRP_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_207/DYNACT2_207_WBCT/DYNACT2_207_WBCT_RECON_TRP_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_TRP="/Volumes/LaCie/DYNACT2/models/DYNACT2_207/DYNACT2_207_ABAD/RESAMPLED/DYNACT2_207_WBCT_TO_DYNACT_TRP_INIT.txt"

DYNACT_ABAD_VOL1="/Volumes/LaCie/DYNACT2/models/DYNACT2_207/DYNACT2_207_ABAD/RESAMPLED/VOLUME_1_RESAMPLED.nii"
OUTPUT_PATH="/Volumes/LaCie/DYNACT2/models/DYNACT2_207/DYNACT2_207_ABAD/RESAMPLED"

# Registration
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\" DYNACT2_207_MC1 \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\" DYNACT2_207_TRP \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd

# Transformation
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd

#--------------
# DYNACT2_208
#--------------
WBCT_MC1_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_208/DYNACT2_208_WBCT/DYNACT2_208_WBCT_RECON_MC1_REORIENT.nii"
WBCT_MC1_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_208/DYNACT2_208_WBCT/DYNACT2_208_WBCT_RECON_MC1_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_MC1="/Volumes/LaCie/DYNACT2/models/DYNACT2_208/DYNACT2_208_ABAD/RESAMPLED/DYNACT2_208_WBCT_TO_DYNACT_MC1_INIT.txt"

WBCT_TRP_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_208/DYNACT2_208_WBCT/DYNACT2_208_WBCT_RECON_TRP_REORIENT.nii"
WBCT_TRP_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_208/DYNACT2_208_WBCT/DYNACT2_208_WBCT_RECON_TRP_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_TRP="/Volumes/LaCie/DYNACT2/models/DYNACT2_208/DYNACT2_208_ABAD/RESAMPLED/DYNACT2_208_WBCT_TO_DYNACT_TRP_INIT.txt"

DYNACT_ABAD_VOL1="/Volumes/LaCie/DYNACT2/models/DYNACT2_208/DYNACT2_208_ABAD/RESAMPLED/VOLUME_1_RESAMPLED.nii"
OUTPUT_PATH="/Volumes/LaCie/DYNACT2/models/DYNACT2_208/DYNACT2_208_ABAD/RESAMPLED"

# Registration
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\" DYNACT2_208_MC1 \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\" DYNACT2_208_TRP \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd

# Transformation
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd

#--------------
# DYNACT2_209
#--------------
WBCT_MC1_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_209/DYNACT2_209_WBCT/DYNACT2_209_WBCT_RECON_MC1_REORIENT.nii"
WBCT_MC1_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_209/DYNACT2_209_WBCT/DYNACT2_209_WBCT_RECON_MC1_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_MC1="/Volumes/LaCie/DYNACT2/models/DYNACT2_209/DYNACT2_209_ABAD/RESAMPLED/DYNACT2_209_WBCT_TO_DYNACT_MC1_INIT.txt"

WBCT_TRP_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_209/DYNACT2_209_WBCT/DYNACT2_209_WBCT_RECON_TRP_REORIENT.nii"
WBCT_TRP_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_209/DYNACT2_209_WBCT/DYNACT2_209_WBCT_RECON_TRP_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_TRP="/Volumes/LaCie/DYNACT2/models/DYNACT2_209/DYNACT2_209_ABAD/RESAMPLED/DYNACT2_209_WBCT_TO_DYNACT_TRP_INIT.txt"

DYNACT_ABAD_VOL1="/Volumes/LaCie/DYNACT2/models/DYNACT2_209/DYNACT2_209_ABAD/RESAMPLED/VOLUME_1_RESAMPLED.nii"
OUTPUT_PATH="/Volumes/LaCie/DYNACT2/models/DYNACT2_209/DYNACT2_209_ABAD/RESAMPLED"

# Registration
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\" DYNACT2_209_MC1 \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\" DYNACT2_209_TRP \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd

# Transformation
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd

#--------------
# DYNACT2_210
#--------------
WBCT_MC1_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_210/DYNACT2_210_WBCT/DYNACT2_210_WBCT_RECON_MC1_REORIENT.nii"
WBCT_MC1_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_210/DYNACT2_210_WBCT/DYNACT2_210_WBCT_RECON_MC1_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_MC1="/Volumes/LaCie/DYNACT2/models/DYNACT2_210/DYNACT2_210_ABAD/RESAMPLED/DYNACT2_210_WBCT_TO_DYNACT_MC1_INIT.txt"

WBCT_TRP_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_210/DYNACT2_210_WBCT/DYNACT2_210_WBCT_RECON_TRP_REORIENT.nii"
WBCT_TRP_SEG_REORIENT="/Volumes/LaCie/DYNACT2/models/DYNACT2_210/DYNACT2_210_WBCT/DYNACT2_210_WBCT_RECON_TRP_PERI_REORIENT.nii"
WBCT_TO_DYNACT_TFM_TRP="/Volumes/LaCie/DYNACT2/models/DYNACT2_210/DYNACT2_210_ABAD/RESAMPLED/DYNACT2_210_WBCT_TO_DYNACT_TRP_INIT.txt"

DYNACT_ABAD_VOL1="/Volumes/LaCie/DYNACT2/models/DYNACT2_210/DYNACT2_210_ABAD/RESAMPLED/VOLUME_1_RESAMPLED.nii"
OUTPUT_PATH="/Volumes/LaCie/DYNACT2/models/DYNACT2_210/DYNACT2_210_ABAD/RESAMPLED"

# Registration
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\" DYNACT2_210_MC1 \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd
cmd="python \"${REGISTRATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\" DYNACT2_210_TRP \"${OUTPUT_PATH}\""
echo $cmd
eval $cmd

# Transformation
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_MC1_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_MC1}\""
echo $cmd
eval $cmd
cmd="python \"${TRANSFORMATION_SCRIPT}\" \"${DYNACT_ABAD_VOL1}\" \"${WBCT_TRP_SEG_REORIENT}\" \"${WBCT_TO_DYNACT_TFM_TRP}\""
echo $cmd
eval $cmd