#!/bin/bash -u
# example usage script. Change path to images and exact image paths/subjects as needed
# Usage: batch_seq_reg.sh <path_to_images>
MOTION_SCRIPT="dynact2/mode_biomech/compute_motion.py"
PATH_TO_IMAGES=$1
OUTPUT_DIR="/dynact2/output/"

for SUBJECT in 001 002 003; do
  WBCT_TO_DYNACT_MC1_TFM="${PATH_TO_IMAGES}DYNACT2_${SUBJECT}/DYNACT2_${SUBJECT}_WBCT/DYNACT2_${SUBJECT}_MC1_WBCT_TO_DYNACT_REG.tfm"
  WBCT_TO_DYNACT_TRP_TFM="${PATH_TO_IMAGES}DYNACT2_${SUBJECT}/DYNACT2_${SUBJECT}_WBCT/DYNACT2_${SUBJECT}_TRP_WBCT_TO_DYNACT_REG.tfm"
  DYNACT_TFMS="${PATH_TO_IMAGES}DYNACT2_${SUBJECT}/DYNACT2_${SUBJECT}_ABAD/SEQ_REG/FinalTFMs"
  WBCT_MC1_POINTS="${OUTPUT_DIR}DYNACT2_${SUBJECT}_PERI_REORIEN_MC1_SCS.txt"
  WBCT_TRP_POINTS="${OUTPUT_DIR}DYNACT2_${SUBJECT}_REORIENT_TR_TRP_SCS.txt"

  cmd="python \"${MOTION_SCRIPT}\" \"${WBCT_TO_DYNACT_MC1_TFM}\" \"${WBCT_TO_DYNACT_TRP_TFM}\" \"${DYNACT_TFMS}\" \"${WBCT_MC1_POINTS}\" \"${WBCT_TRP_POINTS}\" \"${OUTPUT_DIR}\""
  echo $cmd
  eval $cmd
done